@echo off
setx KEICA_TOOL_PATH %~dp0


set /P _KCUSERNAME_="ƒ†[ƒU[–¼: " 
echo %_KCUSERNAME_%

setx KEICA_USERNAME %_KCUSERNAME_%
echo ŠÂ‹«•Ï”KEICA_TOOL_PATH‚ð%KEICA_TOOL_PATH%‚ÉÝ’è‚µ‚Ü‚µ‚½
echo ŠÂ‹«•Ï”KEICA_USERNAME‚ð%_KCUSERNAME_%‚ÉÝ’è‚µ‚Ü‚µ‚½

pause