# -*- coding: utf8 -*-

import os
import sys
import json
import copy
import traceback
import time
import datetime
import importlib
import shutil
import glob

mod = "{}/source/python".format(os.environ["KEICA_TOOL_PATH"])
if mod not in sys.path:
    sys.path.append(mod)

from KcLibs.core.KcProject import *
import KcLibs.core.kc_env as kc_env

logger = kc_env.get_logger("temp")

x = KcProject(logger=logger)
logger.debug("TEMP")
x.set("ZIM", "default")

x.set_tool_config("multi", "KcSceneManager")


data = {'common': {},
 'post_end': {'path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/ZIM_s01c001_anim.fbx'},
 'main': [{u'asset_name': u'ABCDE',
           u'category': u'LO',
           u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                       'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
           'cut': u'001',
           'end': 0,
           'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad.fbx',
           'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
           u'namespace': u'LO_ABCDE_asasad',
           'scene': u'01',
           u'selection': True,
           'start': 0,
           u'take': 0.0,
           u'true_namespace': u'LO_ABCDE_asasad',
           u'type': u'config',
           u'update_at': u'2021/11/23 13:33:10',
           u'update_by': u'amek',
           u'variation': u'asasad',
           u'version': 0.0},
          {u'asset_name': u'ABCDE',
           u'category': u'LO',
           u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                       'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
           'cut': u'001',
           'end': 0,
           'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad_02.fbx',
           'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
           u'namespace': u'LO_ABCDE_asasad_02',
           'scene': u'01',
           u'selection': True,
           'start': 0,
           u'take': 0.0,
           u'true_namespace': u'LO_ABCDE_asasad',
           u'type': u'both',
           u'update_at': u'2021/11/23 13:33:10',
           u'update_by': u'amek',
           u'variation': u'asasad',
           u'version': 0.0},
          {u'asset_name': u'ABCDE',
           u'category': u'LO',
           u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                       'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
           'cut': u'001',
           'end': 0,
           'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad_03.fbx',
           'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
           u'namespace': u'LO_ABCDE_asasad_03',
           'scene': u'01',
           u'selection': True,
           'start': 0,
           u'take': 0.0,
           u'true_namespace': u'LO_ABCDE_asasad',
           u'type': u'config',
           u'update_at': u'2021/11/23 13:33:10',
           u'update_by': u'amek',
           u'variation': u'asasad',
           u'version': 0.0},
          {u'category': u'CH',
           'config': {'export': False, 'plot': False},
           'cut': u'001',
           'end': 0,
           'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad.fbx',
           'mobu_sotai_path': False,
           u'namespace': u'CH_tsukikoQuad',
           'scene': u'01',
           u'selection': True,
           'start': 0,
           u'take': 2.0,
           u'true_namespace': u'CH_tsukikoQuad',
           u'type': u'both',
           u'update_at': u'2021/11/18 01:17:16',
           u'update_by': u'amek'}],
 'post_main': [{u'asset_name': u'ABCDE',
                u'category': u'LO',
                u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                            'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
                'cut': u'001',
                'end': 0,
                'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad.fbx',
                'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
                u'namespace': u'LO_ABCDE_asasad',
                'scene': u'01',
                u'selection': True,
                'start': 0,
                u'take': 0.0,
                u'true_namespace': u'LO_ABCDE_asasad',
                u'type': u'config',
                u'update_at': u'2021/11/23 13:33:10',
                u'update_by': u'amek',
                u'variation': u'asasad',
                u'version': 0.0},
               {u'asset_name': u'ABCDE',
                u'category': u'LO',
                u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                            'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
                'cut': u'001',
                'end': 0,
                'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad_02.fbx',
                'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
                u'namespace': u'LO_ABCDE_asasad_02',
                'scene': u'01',
                u'selection': True,
                'start': 0,
                u'take': 0.0,
                u'true_namespace': u'LO_ABCDE_asasad',
                u'type': u'both',
                u'update_at': u'2021/11/23 13:33:10',
                u'update_by': u'amek',
                u'variation': u'asasad',
                u'version': 0.0},
               {u'asset_name': u'ABCDE',
                u'category': u'LO',
                u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                            'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
                'cut': u'001',
                'end': 0,
                'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad_03.fbx',
                'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
                u'namespace': u'LO_ABCDE_asasad_03',
                'scene': u'01',
                u'selection': True,
                'start': 0,
                u'take': 0.0,
                u'true_namespace': u'LO_ABCDE_asasad',
                u'type': u'config',
                u'update_at': u'2021/11/23 13:33:10',
                u'update_by': u'amek',
                u'variation': u'asasad',
                u'version': 0.0},
               {u'category': u'CH',
                'config': {'export': False, 'plot': False},
                'cut': u'001',
                'end': 0,
                'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad.fbx',
                'mobu_sotai_path': False,
                u'namespace': u'CH_tsukikoQuad',
                'scene': u'01',
                u'selection': True,
                'start': 0,
                u'take': 2.0,
                u'true_namespace': u'CH_tsukikoQuad',
                u'type': u'both',
                u'update_at': u'2021/11/18 01:17:16',
                u'update_by': u'amek'}],
 'post_primary': {'path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/ZIM_s01c001_anim.fbx', 
                  "start": 10, 
                  "end": 100,
                  "fps": 24},
 'primary': {'assets': [{u'asset_name': u'ABCDE',
                         u'category': u'LO',
                         u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                                     'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
                         'cut': u'001',
                         'end': 0,
                         'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad.fbx',
                         'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
                         u'namespace': u'LO_ABCDE_asasad',
                         'scene': u'01',
                         u'selection': True,
                         'start': 0,
                         u'take': 0.0,
                         u'true_namespace': u'LO_ABCDE_asasad',
                         u'type': u'config',
                         u'update_at': u'2021/11/23 13:33:10',
                         u'update_by': u'amek',
                         u'variation': u'asasad',
                         u'version': 0.0},
                        {u'asset_name': u'ABCDE',
                         u'category': u'LO',
                         u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                                     'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
                         'cut': u'001',
                         'end': 0,
                         'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad_02.fbx',
                         'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
                         u'namespace': u'LO_ABCDE_asasad_02',
                         'scene': u'01',
                         u'selection': True,
                         'start': 0,
                         u'take': 0.0,
                         u'true_namespace': u'LO_ABCDE_asasad',
                         u'type': u'both',
                         u'update_at': u'2021/11/23 13:33:10',
                         u'update_by': u'amek',
                         u'variation': u'asasad',
                         u'version': 0.0},
                        {u'asset_name': u'ABCDE',
                         u'category': u'LO',
                         u'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_export.json',
                                     'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/config/LO_ABCDE_asasad_plot.json'},
                         'cut': u'001',
                         'end': 0,
                         'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_LO_ABCDE_asasad_03.fbx',
                         'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/LO/ABCDE/MB/LO_ABCDE_asasad_sotai_t00.fbx',
                         u'namespace': u'LO_ABCDE_asasad_03',
                         'scene': u'01',
                         u'selection': True,
                         'start': 0,
                         u'take': 0.0,
                         u'true_namespace': u'LO_ABCDE_asasad',
                         u'type': u'config',
                         u'update_at': u'2021/11/23 13:33:10',
                         u'update_by': u'amek',
                         u'variation': u'asasad',
                         u'version': 0.0},
                        {u'category': u'CH',
                         'config': {'export': False, 'plot': False},
                         'cut': u'001',
                         'end': 0,
                         'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad.fbx',
                         'mobu_sotai_path': False,
                         u'namespace': u'CH_tsukikoQuad',
                         'scene': u'01',
                         u'selection': True,
                         'start': 0,
                         u'take': 2.0,
                         u'true_namespace': u'CH_tsukikoQuad',
                         u'type': u'both',
                         u'update_at': u'2021/11/18 01:17:16',
                         u'update_by': u'amek'}],
             'end': 0,
             'fps': 24,
             'path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/edit/ZIM_s01c001_anim_t1_01_amek.fbx',
             'start': 0}}


data = {'common': {},
 'main': [{u'asset_name': u'tsukikoQuad',
           u'category': u'CH',
           'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_export.json',
                      'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_plot.json'},
           'cut': u'001',
           'end': 120,
           'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad.fbx',
           'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/CH_tsukikoQuad_sotai_t02.fbx',
           u'namespace': u'CH_tsukikoQuad',
           'scene': u'01',
           u'selection': True,
           'start': 0,
           u'take': 2.0,
           u'true_namespace': u'CH_tsukikoQuad',
           u'type': u'both',
           u'update_at': u'2021/11/19 03:05:35',
           u'update_by': u'amek',
           u'version': 2.0},
          {u'asset_name': u'tsukikoQuad',
           u'category': u'CH',
           'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_export.json',
                      'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_plot.json'},
           'cut': u'001',
           'end': 120,
           'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad_02.fbx',
           'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/CH_tsukikoQuad_sotai_t02.fbx',
           u'namespace': u'CH_tsukikoQuad_02',
           'scene': u'01',
           u'selection': True,
           'start': 0,
           u'take': 2.0,
           u'true_namespace': u'CH_tsukikoQuad',
           u'type': u'both',
           u'update_at': u'2021/11/19 03:05:35',
           u'update_by': u'amek',
           u'version': 2.0},
          {'category': 'camera',
           'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/camera/MB/config/cam_s00c000_export.json',
                      'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/camera/MB/config/cam_s00c000_plot.json'},
           'cut': u'001',
           'end': 120,
           'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_cam_s01c001.fbx',
           'mobu_sotai_path': False,
           'namespace': u'cam_s01c001',
           'scene': u'01',
           'start': 0}],
 'post_end': {'end': 120,
              'fps': 24,
              'movie_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/movie_convert/MB/ZIM_s01c001_MB.mov',
              'path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/ZIM_s01c001_anim.fbx',
              'shot_name': 's01c001',
              'start': 0},
 'post_main': [{u'asset_name': u'tsukikoQuad',
                u'category': u'CH',
                'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_export.json',
                           'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_plot.json'},
                'cut': u'001',
                'end': 120,
                'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad.fbx',
                'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/CH_tsukikoQuad_sotai_t02.fbx',
                u'namespace': u'CH_tsukikoQuad',
                'scene': u'01',
                u'selection': True,
                'start': 0,
                u'take': 2.0,
                u'true_namespace': u'CH_tsukikoQuad',
                u'type': u'both',
                u'update_at': u'2021/11/19 03:05:35',
                u'update_by': u'amek',
                u'version': 2.0},
               {u'asset_name': u'tsukikoQuad',
                u'category': u'CH',
                'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_export.json',
                           'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_plot.json'},
                'cut': u'001',
                'end': 120,
                'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad_02.fbx',
                'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/CH_tsukikoQuad_sotai_t02.fbx',
                u'namespace': u'CH_tsukikoQuad_02',
                'scene': u'01',
                u'selection': True,
                'start': 0,
                u'take': 2.0,
                u'true_namespace': u'CH_tsukikoQuad',
                u'type': u'both',
                u'update_at': u'2021/11/19 03:05:35',
                u'update_by': u'amek',
                u'version': 2.0},
               {'category': 'camera',
                'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/camera/MB/config/cam_s00c000_export.json',
                           'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/camera/MB/config/cam_s00c000_plot.json'},
                'cut': u'001',
                'end': 120,
                'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_cam_s01c001.fbx',
                'mobu_sotai_path': False,
                'namespace': u'cam_s01c001',
                'scene': u'01',
                'start': 0}],
 'post_primary': {'path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/ZIM_s01c001_anim.fbx'},
 'primary': {'assets': [{u'asset_name': u'tsukikoQuad',
                         u'category': u'CH',
                         'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_export.json',
                                    'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_plot.json'},
                         'cut': u'001',
                         'end': 120,
                         'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad.fbx',
                         'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/CH_tsukikoQuad_sotai_t02.fbx',
                         u'namespace': u'CH_tsukikoQuad',
                         'scene': u'01',
                         u'selection': True,
                         'start': 0,
                         u'take': 2.0,
                         u'true_namespace': u'CH_tsukikoQuad',
                         u'type': u'both',
                         u'update_at': u'2021/11/19 03:05:35',
                         u'update_by': u'amek',
                         u'version': 2.0},
                        {u'asset_name': u'tsukikoQuad',
                         u'category': u'CH',
                         'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_export.json',
                                    'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/config/CH_tsukikoQuad_plot.json'},
                         'cut': u'001',
                         'end': 120,
                         'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_anim_CH_tsukikoQuad_02.fbx',
                         'mobu_sotai_path': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/CH/tsukikoQuad/MB/CH_tsukikoQuad_sotai_t02.fbx',
                         u'namespace': u'CH_tsukikoQuad_02',
                         'scene': u'01',
                         u'selection': True,
                         'start': 0,
                         u'take': 2.0,
                         u'true_namespace': u'CH_tsukikoQuad',
                         u'type': u'both',
                         u'update_at': u'2021/11/19 03:05:35',
                         u'update_by': u'amek',
                         u'version': 2.0},
                        {'category': 'camera',
                         'config': {'export': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/camera/MB/config/cam_s00c000_export.json',
                                    'plot': 'E:/works/client/keica/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/camera/MB/config/cam_s00c000_plot.json'},
                         'cut': u'001',
                         'end': 120,
                         'mobu_edit_export_path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/master/export/ZIM_s01c001_cam_s01c001.fbx',
                         'mobu_sotai_path': False,
                         'namespace': u'cam_s01c001',
                         'scene': u'01',
                         'start': 0}],
             'end': 120,
             'fps': 24,
             'path': u'E:/works/client/keica/_942_ZIZ/3D/s01/c001/edit/ZIM_s01c001_anim_t01_02_amek_lo.fbx',
             'start': 0}}
piece = "mobu_edit_export"
piece = "mobu_edit_export_varidate"

results = x.puzzle_play(x.tool_config["puzzle"][piece], 
                    data, 
                    {}, 
                    ["primary", "main", "post_primary", "post_main", "post_end"])

for result in results[1]:
    print(result)