info:
    name: project

data:
    extra_fields: 
        asset_root: <root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets

    general: 
        root_directory: "X:/Project/_942_ZIZ"
        fps: 24

        padding: 
            "<scene>": 2
            "<cut>": 3
            "<take>": 2
            "<version>": 2

    asset: 
        category:
            - BG
            - camera
            - CH
            - LO
            - POSE
            - PP 

        namespaces:
            default:
                "<category>_<asset_name>"
            LO:
                "<category>_<asset_name>_<variation>"
            camera:
                cam_s<scene>c<cut>

        meta:
            - namespace
            - asset_name
            - variation
            - take
            - version
            - category
            - update_at
            - update_by

        mobu:
            paths:
                default:
                    rig: <asset_root>/<category>/<asset_name>/MB/<category>_<asset_name>_t<take>_<version>.fbx
                    sotai: <asset_root>/<category>/<asset_name>/MB/sotai/<category>_<asset_name>_sotai_t<take>.fbx
                    config: <asset_root>/<category>/<asset_name>/MB/config/<category>_<asset_name>_<config_type>.json
                    edit_export: "<root_directory>/3D/s<scene>/c<cut>/master/export/<project>_s<scene>c<cut>_anim_<namespace>.fbx"


                LO:
                    rig: <asset_root>/<category>/<asset_name>/MB/<category>_<asset_name>_<variation>_t<take>_<version>.fbx
                    sotai: <asset_root>/<category>/<asset_name>/MB/sotai/<category>_<asset_name>_<variation>_sotai_t<take>.fbx
                    config: <asset_root>/<category>/<asset_name>/MB/config/<category>_<asset_name>_<variation>_<config_type>.json
                    edit_export: "<root_directory>/3D/s<scene>/c<cut>/master/export/<project>_s<scene>c<cut>_anim_<namespace>.fbx"

                camera:
                    rig: <asset_root>/<category>/MB/cam_t<take>_<version>.FBX
                    sotai: <asset_root>/<category>/MB/sotai/cam_sotai_t<take>.FBX
                    config: <asset_root>/<category>/MB/config/cam_s00c000_<config_type>.json
                    edit_export: "<root_directory>/3D/s<scene>/c<cut>/master/export/<project>_s<scene>c<cut>_<namespace>.fbx"

        max:
            paths:
                default:
                    edit: ""
                    master: ""
                    edit_movie: ""
                    master_movie: ""


    shot: 
        header:
            "<scene>": "s"
            "<cut>": "c"

        name_pattern: "s<scene>c<cut>"

        progress:
            - anim

        mobu:
            paths:
                edit: <root_directory>/3D/s<scene>/c<cut>/edit/<project>_s<scene>c<cut>_edit_t<take>_<version>_<user>_<progress>.fbx
                master: <root_directory>/3D/s<scene>/c<cut>/master/<project>_s<scene>c<cut>_anim.fbx
                edit_movie: <root_directory>/3D/s<scene>/c<cut>/edit/mov_edit/<project>_s<scene>c<cut>_anim_t<take>_<version>_<user>.mov
                master_movie: <root_directory>/3D/s<scene>/c<cut>/movie_convert/MB/<project>_s<scene>c<cut>_MB.mov

        max:
            paths:
                edit: ""
                master: ""
                edit_movie: ""
                master_movie: ""


    puzzle:
        get_cameras:
            main:
                - name: get cameras
                  piece: KcHooks.pieces.<app>.default.get_cameras
                  description: get camera from scene
        change_camera:
            main:
                - name: change camera
                  piece: KcHooks.pieces.<app>.default.change_camera
                  description: change camera to

        get_assets:
            main:
                - name: get assets
                  piece: KcHooks.pieces.<app>.default.get_assets
                  description: get asset from scene



