info:
  name: project

data:
  extra_fields:
    asset_root: <root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets

  general:
    root_directory: "X:/Project/_942_ZIZ"
    fps: 24

    padding:
      "<scene>": 2
      "<cut>": 3
      "<take>": 2
      "<version>": 2

    network:
      backbarner: "192.168.1.14"

  asset:
    category:
      - BG
      - camera
      - CH
      - LO
      - POSE
      - PP

    namespaces:
      default: "<category>_<asset_name>"
      LO: "<category>_<asset_name>_<variation>"
      camera: cam_s<scene>c<cut>

    meta:
      - namespace
      - asset_name
      - variation
      - take
      - version
      - category
      - update_at
      - update_by

    mobu:
      paths:
        default:
          rig: <asset_root>/<category>/<asset_name>/MB/<category>_<asset_name>_t<take>_<version>.fbx
          sotai: <asset_root>/<category>/<asset_name>/MB/sotai/<category>_<asset_name>_sotai_t<take>.fbx
          config: <asset_root>/<category>/<asset_name>/MB/config/<category>_<asset_name>_<config_type>.json
          edit_export: "<root_directory>/3D/s<scene>/c<cut>/master/export/<project>_s<scene>c<cut>_anim_<namespace>.fbx"
          master_export: "<root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/s<scene>/c<cut>/3D/master/import/<project>_s<scene>c<cut>_anim_<namespace>.fbx"

        LO:
          rig: <asset_root>/<category>/<asset_name>/MB/<category>_<asset_name>_<variation>_t<take>_<version>.fbx
          sotai: <asset_root>/<category>/<asset_name>/MB/sotai/<category>_<asset_name>_<variation>_sotai_t<take>.fbx
          config: <asset_root>/<category>/<asset_name>/MB/config/<category>_<asset_name>_<variation>_<config_type>.json
          edit_export: "<root_directory>/3D/s<scene>/c<cut>/master/export/<project>_s<scene>c<cut>_anim_<namespace>.fbx"
          master_export: "<root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/s<scene>/c<cut>/3D/master/import/<project>_s<scene>c<cut>_anim_<namespace>.fbx"

        camera:
          rig: <asset_root>/<category>/MB/cam_t<take>_<version>.FBX
          sotai: <asset_root>/<category>/MB/sotai/cam_sotai_t<take>.FBX
          config: <asset_root>/<category>/MB/config/cam_s00c000_<config_type>.json
          edit_export: "<root_directory>/3D/s<scene>/c<cut>/master/export/<project>_s<scene>c<cut>_<namespace>.fbx"
          master_export: "<root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/s<scene>/c<cut>/3D/master/import/<project>_s<scene>c<cut>_<namespace>.fbx"

    max:
      paths:
        default:
          rig: <asset_root>/<category>/<asset_name>/<category>_<asset_name>_rig_t<take>_<version>.max
        LO:
          rig: <asset_root>/<category>/<asset_name>/<category>_<asset_name>_<variation>_rig_t<take>_<version>.max
        camera:
          rig: <asset_root>/camera/cam_t<take>_<version>.max
  shot:
    header:
      "<scene>": "s"
      "<cut>": "c"

    name_pattern: "s<scene>c<cut>"

    progress:
      - anim

    camera_name: Merge_Camera

    mobu:
      paths:
        edit: <root_directory>/3D/s<scene>/c<cut>/edit/<project>_s<scene>c<cut>_edit_t<take>_<version>_<user>_<progress>.fbx
        master: <root_directory>/3D/s<scene>/c<cut>/master/<project>_s<scene>c<cut>_anim.fbx
        edit_movie: <root_directory>/3D/s<scene>/c<cut>/edit/mov_edit/<project>_s<scene>c<cut>_anim_t<take>_<version>_<user>.mov
        master_movie: <root_directory>/3D/s<scene>/c<cut>/movie_convert/MB/<project>_s<scene>c<cut>_MB.mov

    max:
      paths:
        edit: <root_directory>/3D/s<scene>/c<cut>/3D/edit/<project>_s<scene>c<cut>_edit_t<take>_<version>_<user>_<progress>.max
        master: <root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/s<scene>/c<cut>/3D/master/<project>_s<scene>c<cut>_anim.max
        rend: <root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/s<scene>/c<cut>/3D/rend/<cell>
        edit_movie: <root_directory>/3D/s<scene>/c<cut>/3D/edit/mov_edit/<project>_s<scene>c<cut>_anim_t<take>_<version>_<user>.avi
        master_movie: <root_directory>/3D/s<scene>/c<cut>/movie_convert/max/<project>_s<scene>c<cut>_max.avi

  composite:
    default:
      paths:
        render: <root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/s<scene>/c<cut>/aep/render/<cell>/<cell_category>/*.*
        sozai: <root_directory>/2020_ikimono_movie/_work/14_partC_Japan/26_animation/s<scene>/c<cut>/aep/_Sozai_test/<cell>/<cell_category>/*.*

  puzzle:
    get_cameras:
      - step: main
        tasks:
          - name: get cameras
            module: KcHooks.pieces.<app>.default.get_cameras
            comment: get camera from scene

    change_camera:
      - step: main
        tasks:
          - name: change camera
            module: KcHooks.pieces.<app>.default.change_camera
            comment: change camera to

    get_assets:
      - step: main
        tasks:
          - name: get assets
            module: KcHooks.pieces.<app>.default.get_assets
            comment: get asset from scene
