info:
    name: project
    parent: ../_base_.yml

data:
  extra_fields: 
    root_directory: K:/DTN
    asset_root: <root_directory>/LO/Asset_keica
    shot_root: <root_directory>/LO

  asset:
    namespaces:
      default: "<category>_<asset_name>"
      LO: "<category>_<asset_name>_<variation>"
      camera: Cam_A<cut>

    mobu:
      paths:
        default:
          rig: <asset_root>/<category>/<category>_<asset_name>_t<take>_<version>.fbx
          sotai: <asset_root>/<category>/sotai/<category>_<asset_name>_sotai_t<take>.fbx
          config: <asset_root>/<category>/models/<category>_<asset_name>_<config_type>.json
          edit_export: "<shot_root>/<part>_<seq>/<part>_<seq>_<cut>/master/export/<project>_<seq>_<cut>_anim_<namespace>.fbx"
          master_export: "<root_directory>/UELO/MB_Data/<part>_<seq>/<part>_<seq>_<cut>/<part>_<seq>_<cut>_<namespace>_<take>_<version>.fbx"

        CH:
          rig: <asset_root>/<category>/<sub_category>/CH_<asset_name>_t<take>_<version>.fbx
          sotai: <asset_root>/<category>/sotai/CH_<asset_name>_sotai_t<take>.fbx
          config: <asset_root>/<category>/models/CH_<asset_name>_<config_type>.json
          edit_export: "<shot_root>/<part>_<seq>/<part>_<seq>_<cut>/master/export/<project>_<seq>_<cut>_anim_<namespace>.fbx"
          master_export: "<root_directory>/UELO/MB_Data/<part>_<seq>/<part>_<seq>_<cut>/<part>_<seq>_<cut>_<namespace>_<take>_<version>.fbx"

        PROPS:
          rig: <asset_root>/<category>/PROPS_<asset_name>_t<take>_<version>.fbx
          sotai: <asset_root>/<category>/sotai/PROPS_<asset_name>_sotai_t<take>.fbx
          config: <asset_root>/<category>/models/PROPS_<asset_name>_<config_type>.json
          edit_export: "<shot_root>/<part>_<seq>/<part>_<seq>_<cut>/master/export/<project>_<seq>_<cut>_anim_<namespace>.fbx"
          master_export: "<root_directory>/UELO/MB_Data/<part>_<seq>/<part>_<seq>_<cut>/<part>_<seq>_<cut>_<namespace>_<take>_<version>.fbx"


        BG:
          rig: <asset_root>/<category>/BG_<asset_name>_t<take>_<version>.fbx
          sotai: <asset_root>/<category>/sotai/BG_<asset_name>_sotai_t<take>.fbx
          config: <asset_root>/<category>/models/BG_<asset_name>_<config_type>.json
          edit_export: "<shot_root>/<part>_<seq>/<part>_<seq>_<cut>/master/export/<project>_<seq>_<cut>_anim_<namespace>.fbx"
          master_export: "<root_directory>/UELO/MB_Data/<part>_<seq>/<part>_<seq>_<cut>/<part>_<seq>_<cut>_<namespace>_<take>_<version>.fbx"

        camera:
          rig: <asset_root>/<category>/MB/cam_t<take>_<version>.FBX
          sotai: <asset_root>/<category>/MB/sotai/cam_sotai_t<take>.FBX
          config: <asset_root>/camera/MB/models/cam_s00c000_<config_type>.json
          edit_export: "<shot_root>/<part>_<seq>/<part>_<seq>_<cut>/master/export/<project>_<seq>_<cut>.fbx"
          master_export: "<root_directory>/UELO/MB_Data/<part>_<seq>/<part>_<seq>_<cut>/<part>_<seq>_<cut>_cam_<take>_<version>.fbx"

  general:
    root_directory: "K:/DTN"

    padding:
      "<scene>": 2
      "<take>": 2
      "<version>": 2  
      "<cut>": -1

  shot:
    name_pattern: "<part>_<seq>_<cut>"
    sequence_name_settings: 
        template: <part>_<seq>
        prefix: ""

    progress:
      - anim

    camera_name: Cam_A0000

    mobu:
      paths:
        edit: <shot_root>/<part>_<seq>/<part>_<seq>_<cut>/<part>_<seq>_<cut>_<take>_<version>_<progress>.fbx
        master: <shot_root>/<part>_<seq>/<part>_<seq>_<cut>/master/<part>_<seq>_<cut>_<take>_<version>_<progress>.fbx
        publish: <root_directory>/UELO/MB_Data/<part>_<seq>/<part>_<seq>_<cut>/work/<part>_<seq>_<cut>_<take>_<version>_plot.fbx

        edit_movie: <shot_root>/mov/<part>_<seq>_<cut>_<take>_<version>_<progress>_<user>.mov
        master_movie: <shot_root>/mov/master/<part>_<seq>_<cut>_<take>_<version>_<progress>_<user>.mov
        publish_movie: <root_directory>/UELO/MB_Data/<part>_<seq>/<part>_<seq>_<cut>/mov/<part>_<seq>_<cut>_<take>_<version>_LO.mov

  puzzle:
    mobu_merge_asset:
      - step: main
        tasks:
          - name: merge asset
            module: KcHooks.pieces.mobu.default.merge_asset
          
          - name: rename camera
            module: KcHooks.pieces.mobu.projects.DTN.merge_rename_camera

    get_assets:
      - step: main
        tasks:
          - name: get assets
            module: KcHooks.pieces.<app>.projects.DTN.get_assets
            comment: get asset from scene

    get_cameras:
      - step: main
        tasks:
          - name: get cameras
            module: KcHooks.pieces.<app>.projects.DTN.get_cameras
            comment: get camera from scene