info:
  name: KcCopySequence

data:
  puzzle:
    copySequence:
      - step: main
        tasks:
          - name: archive
            module: KcHooks.pieces.win.archive_file
            comment: archive edit file
            is_directory: true
            data_key_replace:
              path: source_directory

          - name: copy and rename files
            module: KcHooks.pieces.win.renumber_files
            comment: copy sequence
            data_defaults:
              frame_offset: true
