info:
  name: tool
  parent: ../_base_.yml

data:
  directory: "X:/Project/tools/project/ZIM"
  shot_directory: "X:/Project/_942_ZIZ/3D"
  schema:
    shot:
      shot_name: ""
      paths:
        mobu:
          edit: ""
          master: ""
        max:
          edit: ""
          master: ""

      fields:
        scene: 0
        cut: 0
        take: 0
        version: 0
        progress: anim
        project: ""
        project_variation: ""

      frame:
        start: 0
        end: 0
        fps: 0

      assets: []

  default_shot_name:
    "<project>": "ZIM"
    "<scene>": "01"
    "<cut>": "001"
    "<take>": "01"
    "<version>": "01"

  puzzle:
    mobu_edit_export_varidate:
      - step: primary
        tasks:
          - name: open_file
            module: KcHooks.pieces.mobu.default.file_open
            comment: open file

      - step: main
        tasks:
          - name: export asset
            module: KcHooks.pieces.mobu.default.asset_export
            comment: export asset
            data_defaults:
              mode: varidate

            # conditions:
            #     - category: ["CH", "BG", "PR", "LO"]
            data_key_replace:
              export_path: mobu_edit_export_path

          #- name: export camera
          #  module: KcHooks.pieces.mobu.default.camera_export
          #  comment: export camera
          #  mode: varidate
          #  conditions:
          #      - category: [cam]

          #  data_key_replace:
          #      export_path: mobu_edit_export_path

    mobu_edit_export:
      - step: primary
        tasks:
          - name: archive
            module: KcHooks.pieces.win.archive_file
            comment: archive edit file

          - name: open_file
            module: KcHooks.pieces.mobu.default.file_open
            comment: open file
            data_defaults:
              force: true

          - name: plot_all
            module: KcHooks.pieces.mobu.default.plot_all
            comment: plot all
            interpolate: Stepped

          - name: change scene time
            module: KcHooks.pieces.mobu.default.change_time
            comment: "change scene time. result set to pass_data"
            data_defaults:
              fps: 24
              mode: change

          # - name: plot_all
          #   module: KcHooks.pieces.mobu.default.plot_all
          #   comment: plot all
          #   data_key_replace:
          #       start: "@start"
          #       end: "@end"
          #       fps: "@fps"

      - step: main
        tasks:
          # - name: koma save
          #   module: KcHooks.pieces.mobu.default.get_koma
          #   comment: save koma config

            - name: export asset
              module: KcHooks.pieces.mobu.default.asset_export
              comment: export
              key_name: plot
              data_key_replace:
                export_path: mobu_edit_export_path
                start: "@start"
                end: "@end"
                fps: "@fps"

          # - name: export camera
          #   module: KcHooks.pieces.mobu.default.camera_export
          #   comment: export camera
          #   data_key_replace:
          #       export_path: mobu_edit_export_path

      - step: post_primary
        tasks:
          - name: create
            module: KcHooks.pieces.mobu.default.file_open
            comment: ""

            data_defaults:
              new: true

            data_key_replace:
              start: "@start"
              end: "@end"
              fps: "@fps"

          - name: adject assets
            module: KcHooks.pieces.mobu.default.adjust_scene_assets
            comment: check assets and adject them. delete if not exists in asset list

      - step: post_main
        tasks:
          - name: story clip create
            module: KcHooks.pieces.mobu.default.story_create
            comment: create story clip

            data_defaults:
              key_name: plot

            data_key_replace:
              export_path: mobu_edit_export_path
              asset_path: mobu_sotai_path
              start: "@start"
              end: "@end"
              fps: "@fps"

      - step: post_end
        tasks:
          - name: cam_setup
            module: KcHooks.pieces.mobu.default.camera_setup
            comment: ""
            data_key_replace:
              camera: "@camera"
              width: "@width"
              height: "@height"

          - name: setup scene
            module: KcHooks.pieces.mobu.default.setup_scene
            comment: ""

          - name: file_save
            module: KcHooks.pieces.mobu.default.file_save
            comment: ""
            data_key_replace:
              path: mobu_master_path
              start: "@start"
              end: "@end"
              fps: "@fps"

          - name: render_scene
            module: KcHooks.pieces.mobu.default.render_scene
            comment: ""
            data_key_replace:
              start: "@start"
              end: "@end"
              fps: "@fps"

    mobu_master_export:
      - step: primary
        tasks:
          - name: open
            module: KcHooks.pieces.mobu.default.file_open
            comment: ""

          - name: change scene time
            module: KcHooks.pieces.mobu.default.change_time
            comment: "change scene time. result set to pass_data"
            data_defaults:
              fps: 24
              mode: change

          - name: plot_all
            module: KcHooks.pieces.mobu.default.plot_all
            comment: plot all
            data_key_replace:
              start: "@start"
              end: "@end"
              fps: "@fps"

          - name: remove koma
            module: KcHooks.pieces.win.remove_files
            comment: remove koma files
            data_defaults:
              patterns:
                - root: mobu_master_export_path
                  target: ../import/*_koma.json

      - step: main
        tasks:
          - name: koma save
            module: KcHooks.pieces.mobu.default.get_koma
            comment: save koma config
            data_key_replace:
              path: mobu_master_export_path
              start: "@start"
              end: "@end"
              fps: "@fps"

          - name: export asset
            module: KcHooks.pieces.mobu.default.asset_export
            comment: export asset
            data_key_replace:
              export_path: mobu_master_export_path
              start: "@start"
              end: "@end"
              fps: "@fps"

      - step: post_main
        tasks:
          - name:
            module: KcHooks.pieces.mobu.default.rename_namespace
            comment: remove namespace numbers
            data_key_replace:
              path: mobu_master_export_path

    convert:
      - step: main
        tasks:
          - name: execute command line
            module: KcHooks.pieces.win.execute_command
            comment: through pieces from command line
            data_defaults:
              keys: max_import
              app_environ: PT_DISPATCHER_MAX

    mobu_master_export_varidate:
      - step: primary
        tasks:
          - name: open_file
            module: KcHooks.pieces.mobu.default.file_open
            comment: open file

      - step: main
        tasks:
          - name: export asset
            module: KcHooks.pieces.mobu.default.asset_export
            comment: export asset
            data_defaults:
              mode: master_varidate
            # conditions:
            #     - category: ["CH", "BG", "PR", "LO"]
            data_key_replace:
              export_path: mobu_master_export_path

    max_import:
      - step: primary
        tasks:
          - name: convert project to object
            module: KcHooks.pieces.win.convert_project
            comment: convert str to object
  
      - step: main
        tasks:
          - name: open
            module: KcHooks.pieces.max.default.file_open
            comment: open each assets
            data_key_replace:
              path: max_asset_path

          - name: import camera
            module: KcHooks.pieces.max.default.import_camera
            comment: ""
            conditions:
              category: camera

            data_key_replace:
              asset_path: max_asset_path
              import_path: mobu_master_export_path

          - name: import asset
            module: KcHooks.pieces.max.default.import_asset
            comment: ""
            data_key_replace:
              asset_path: max_asset_path
              import_path: mobu_master_export_path

          - name: save asset
            module: KcHooks.pieces.max.default.file_save

            data_defaults:
              replace_ext: [".fbx", ".max"]

            comment: ""
            data_key_replace:
              save_path: mobu_master_export_path

      - step: post_primary
        tasks:
          - name: open base file
            module: KcHooks.pieces.max.default.create_base_scene
            comment: import base file
            data_defaults:
              base_path: "X:/Project/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_Tool/base.max"

      - step: post_main
        tasks:
          - name: merge asset
            replace_ext: [".fbx", ".max"]
            module: KcHooks.pieces.max.default.file_merge
            comment: "merge asset files"
            data_defaults:
              render_element_path: X:/Project/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_Tool/rps/<category>_<namespace>_RenderElements.rps

            data_key_replace:
              path: mobu_master_export_path

      - step: post_end
        tasks:
          - name: setup render setting
            module: KcHooks.pieces.max.default.set_render_setting
            comment: set render setting
            data_key_replace:
              width: "@width"
              height: "@height"
              fps: "@fps"
              start: "@start"
              end: "@end"

          - name: archive
            module: KcHooks.pieces.win.archive_file
            comment: archive edit file

          - name: save file
            module: KcHooks.pieces.max.default.file_save
            comment: save max file
            data_key_replace:
              save_path: path
              width: "@width"
              height: "@height"
              fps: "@fps"
              start: "@start"
              end: "@end"

          - name: open
            module: KcHooks.pieces.max.default.file_open
            comment: open save file

          - name: render scene
            module: KcHooks.pieces.max.default.render_scene
            comment: render scene
            data_defaults:
              scale_percent: 50

            data_key_replace:
              start: "@start"
              end: "@end"
              fps: "@fps"

          - name: create directories
            module: KcHooks.pieces.win.projects.ZIM.create_directories
            comment: hard code & crete from pass_data <create_directories> keys

      - step: separate_main
        tasks:
          - name: open base file
            module: KcHooks.pieces.max.default.create_base_scene
            comment: import base file

            data_defaults:
              base_path: "X:/Project/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_3D_assets/camera/base.max"

          - name: merge assets
            replace_ext: [".fbx", ".max"]
            module: KcHooks.pieces.max.default.file_merges
            comment: "merge asset files"
            data_defaults:
              render_element_path: X:/Project/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_Tool/rps/<namespace>_RenderElements.rps

            data_key_replace:
              path: mobu_master_export_path

          - name: setup render setting
            module: KcHooks.pieces.max.default.set_render_setting
            comment: set render setting
            data_key_replace:
              width: "@width"
              height: "@height"
              fps: "@fps"
              start: "@start"
              end: "@end"

          - name: archive
            module: KcHooks.pieces.win.archive_file
            comment: archive edit file

          - name: save file
            module: KcHooks.pieces.max.default.file_save
            comment: save max file
            data_key_replace:
              save_path: path
              width: "@width"
              height: "@height"
              fps: "@fps"
              start: "@start"
              end: "@end"

          - name: open
            module: KcHooks.pieces.max.default.file_open
            comment: open save file

          - name: render scene
            module: KcHooks.pieces.max.default.render_scene
            comment: render scene
            data_defaults:
              scale_percent: 50

            data_key_replace:
              start: "@start"
              end: "@end"
              fps: "@fps"

          - name: separate_by_element
            module: KcHooks.pieces.max.ZIZ.separate_by_element
            comment: just for this project
            conditions:
              - split_flg: true
            render_element_path: X:/Project/_942_ZIZ/2020_ikimono_movie/_work/14_partC_Japan/26_animation/_Tool/rps

    mobu_edit_render:
      - step: primary
        tasks:
          - name: open
            module: KcHooks.pieces.mobu.default.file_open
            comment: ""

          # - name: change scene time
          #   module: KcHooks.pieces.mobu.default.change_time
          #   comment: "change scene time. result set to pass_data"
          #   fps: 24
          #   mode: change

          - name: render
            module: KcHooks.pieces.mobu.default.render_scene
            comment: "render scene"
            data_key_replace:
              start: "@start"
              end: "@end"
              fps: "@fps"

      - step: closure
        tasks:
          - name: revert scene time
            module: KcHooks.pieces.mobu.default.change_time
            comment: "revert scene time"
            mode: revert
